### ISSUE TITLE
DLL load

### ISSUE THREAD

**Issue by s1im3r00** [S3cur3Th1sSh1t/Invoke-SharpLoader#1]
is it possible to load DLL with it?

**Comment by S3cur3Th1sSh1t** [comment]
I didn't test that so far. I'm using `EntryPoint.Invoke()` to start the binaries EntryPoint. I think, that this won't work for DLLs.
But you can also modify the script and use `[System.Reflection.Assembly]::Load()` instead, this will load the DLL so that you can execute public functions manually.

**Comment by s1im3r00** [comment]
i want to try loading the dll into memory ... is it possible to share the Invoke-ReflectivePEInjection script?

**Comment by S3cur3Th1sSh1t** [comment]
https://raw.githubusercontent.com/S3cur3Th1sSh1t/Creds/master/PowershellScripts/Invoke-ReflectivePEInjection.ps1
